const testResponse = {
  data: {
    products: [
      {
        category: ["beeproducts"],
        price: 13.95,
        previousPrice: 0,
        countInStock: 6,
        rating: 0,
        numReviews: 0,
        isPromo: false,
        isPublished: true,
        _id: "60ce1f85f82d8fe487f7f445",
        name: "Bee pollen ",
        user: "60c654a986f5c3bd9967f046",
        image: "/public/images/ipadpro11_-3-6-1624373509347.jpg",
        description:
          "Bee pollen is rich in nutrients. These are mainly highly valuable proteins and lipids as well as vitamins A, B, K, E and P. It contains a lot of easily digestible macro- and microelements. We encourage you to consume it, especially during the autumn and winter solstice.\n\nDissolve two full teaspoons of pollen in mild-warm water (you can add a bit honey) and leave for a few hours, preferably overnight. Drink the prepared drink first thing in the morning - on an empty stomach.\n\nBenefits of bee pollen:\n- helps with cardiovascular disease, atherosclerosis, hypertension;\n- detoxifies and regenerates the liver;\n- diseases of the prostate gland;\n- helps with anemia;\n- affects the overall improvement of eyesight;\n- strengthens the nervous system;\n- increases psychological and physical resistance;\n- strengthens the skin, hair and nails;\n\nNote: Due to the high risk of allergies, it is best to introduce bee products into the diet gradually, observing the body's reaction. Not recommended for young children under 4 years of age.\n\nOrigin: Poland\n\nNet weight: 500 g\n ",
        brand: "Pasieka Slodka Kraina",
        capacity: "500 g",
        capacityDropdown: [],
        countryOfOrigin: "",
        reviews: [],
        createdAt: "2021-06-19T16:47:01.562Z",
        updatedAt: "2021-07-20T10:34:21.033Z",
        __v: 0,
      },
      {
        category: ["beeproducts"],
        price: 9.45,
        previousPrice: 0,
        countInStock: 3,
        rating: 0,
        numReviews: 0,
        isPromo: false,
        isPublished: true,
        _id: "60ce21c5f82d8fe487f7f446",
        name: "Bee bread",
        user: "60c654a986f5c3bd9967f046",
        image: "/public/images/ipadpro11_-2-9-1-1624121775117.jpg",
        description:
          "Bee bread is the staple food of bees that they produce inside the hive. It is made of a mixture of pollen and the saliva of worker bees. The resulting pollen lumps are transported by bees to the hive, then packed in combs where they ferment with lactic acid. Bee bread can be recognized by their dark brown color and their lumpy, irregular shape. It has a harder consistency compared to pollen. The taste is resinous and slightly acidic.\nBread is considered a very valuable food product. It contains essential amino acids that are easily absorbed by our body, and which we must take with food because our body cannot produce them by self. There are both saturated and unsaturated fats in the bee bread. We find carbohydrates and nucleic acids in it. It is a rich source of vitamins A and E. Additionally, it contains vitamin C and most of the B vitamins - pantothenic acid, folic acid, biotin, vit. B1, B2, B3. It also contains minerals such as magnesium, calcium, sodium and potassium, and minimal amounts of copper, zinc, silicon, chromium and manganese.\nBee bread like a pollen, should be used in a ground form. You can add it to water and drinks, yoghurts, breakfast dishes or eat directly from a spoon, for example with honey.\n\nBenefits of bee bread:\n- helps to keep skin, hair and nails in good condition;\n- helps with neurosis, depression and intense mental effort;\n- helps with ulcers, diarrhea and liver problems;\n- helps with anemia, in periods of severe fatigue;\n- valuable after surgery;\n- in post-infarction conditions;\n\nNote: Due to the high risk of allergies, it is best to introduce bee products into the diet gradually, observing the body's reaction. Not recommended for young children under 4 years of age.\n\nOrigin: Poland\n\nNet weight: 200g",
        brand: "Pasieka Slodka Kraina",
        capacity: "100 g",
        capacityDropdown: [],
        countryOfOrigin: "",
        reviews: [],
        createdAt: "2021-06-19T16:56:37.514Z",
        updatedAt: "2021-07-20T10:34:00.373Z",
        __v: 0,
      },
      {
        category: ["beeproducts"],
        price: 15.95,
        previousPrice: 0,
        countInStock: 6,
        rating: 0,
        numReviews: 0,
        isPromo: false,
        isPublished: true,
        _id: "60d1c1568979637cf902ac62",
        name: "Raw propolis",
        user: "60c654a986f5c3bd9967f046",
        image: "/public/images/ipadpro11_-9-2-1625311009684.jpg",
        description:
          "Propolis is produced by bees from resin, wax and balsamic substances obtained from plant buds. It is of great importance in maintaining hygiene in hives, due to its bacteriostatic, bactericidal, protozoicidal and fungicidal properties. It is recommended for use as a disinfectant for wounds and as a means of strengthening the body's resistance. It contains organic acids, lipid-protein substances, flavones, vitamins E, H, P, B and provitamin A as well as elements (calcium, manganese, magnesium, zinc, iron, algae, silver, sodium, potassium, chromium, titanium, vanadium, barium, silicon, copper) The color of propolis depends on the plants it is harvested from. Its color can range from orange, through red, green, brown and black. The taste of propolis is balsamic and, by some, judged to be tart, bitter and pungent. It has a strong and distinct yet pleasant fragrance.\n\nOther properties of propolis:\n- inhibits the inflammation of the throat, larynx and mouth;\n- soothing in skin diseases, accelerates wound healing;\n- protects blood vessels against blood clots;\n- improves the early stage of viral hepatitis;\n- anti-rheumatic;\n- stimulating blood circulation;\n\nNote: Due to the high risk of allergies, it is best to introduce bee products into the diet gradually, observing the body's reaction. Not recommended for young children under 4 years of age.\n\nOrigin: Poland\n\nNet weight: 50g\n\nThe energy value in 100 g of the product is about 2233 kJ / 535 kcal, fat 31 g, including saturated acids 5.4 g; carbohydrates 62 g, including sugars 0 g; protein 1.9 g; salt 0.0 g;",
        brand: "",
        capacity: "50 g",
        capacityDropdown: [],
        countryOfOrigin: "",
        reviews: [],
        createdAt: "2021-06-22T10:54:14.520Z",
        updatedAt: "2021-07-21T11:47:52.172Z",
        __v: 0,
      },
      {
        category: ["beeproducts"],
        price: 7.95,
        previousPrice: 0,
        countInStock: 6,
        rating: 0,
        numReviews: 0,
        isPromo: false,
        isPublished: true,
        _id: "60d1c47d8979637cf902ac63",
        name: "Bee pollen ",
        user: "60c654a986f5c3bd9967f046",
        image: "/public/images/ipadpro11_-5-4-2-1625310989590.jpg",
        description:
          "Bee pollen is rich in nutrients. These are mainly highly valuable proteins and lipids as well as vitamins A, B, K, E and P. It contains a lot of easily digestible macro- and microelements. We encourage you to consume it, especially during the autumn and winter solstice.\n\nDissolve two full teaspoons of pollen in mild-warm water (you can add a bit honey) and leave for a few hours, preferably overnight. Drink the prepared drink first thing in the morning - on an empty stomach.\n\nBenefits of bee pollen:\n- helps with cardiovascular disease, atherosclerosis, hypertension;\n- detoxifies and regenerates the liver;\n- diseases of the prostate gland;\n- helps with anemia;\n- affects the overall improvement of eyesight;\n- strengthens the nervous system;\n- increases psychological and physical resistance;\n- strengthens the skin, hair and nails;\n\nNote: Due to the high risk of allergies, it is best to introduce bee products into the diet gradually, observing the body's reaction. Not recommended for young children under 4 years of age.\n\nOrigin: Poland\n\nNet weight: 200 g \n\n",
        brand: "",
        capacity: "200 g",
        capacityDropdown: [],
        countryOfOrigin: "",
        reviews: [],
        createdAt: "2021-06-22T11:07:41.146Z",
        updatedAt: "2021-07-20T10:27:55.461Z",
        __v: 0,
      },
      {
        category: ["additives", "creamedhoneys", "beeproducts", "honeys"],
        price: 5.95,
        previousPrice: 0,
        countInStock: 6,
        rating: 0,
        numReviews: 0,
        isPromo: false,
        isPublished: true,
        _id: "60d1ca0c8979637cf902ac64",
        name: "Propolis in honey",
        user: "60c654a986f5c3bd9967f046",
        image: "/public/images/ipadpro11_-2-3-5-1625310975783.jpg",
        description:
          "The health richness of propolis combined with natural honey. A great blend for making strengthening drinks. It has a simple composition and carefully selected ingredients.\n\nOrigin: Poland\n\nIngredients: pure honey 99.5%, propolis 0.5%\n\nEnergy value in 100g of product is around 1400 kJ / 329 kcal, fat 0 g; carbohydrates 80 g, including sugars 74 g; protein 0.3 g; salt.0 g.",
        brand: "",
        capacity: "220 g",
        capacityDropdown: [],
        countryOfOrigin: "",
        reviews: [],
        createdAt: "2021-06-22T11:31:24.170Z",
        updatedAt: "2021-07-20T10:27:15.738Z",
        __v: 1,
      },
      {
        category: ["additives", "creamedhoneys", "beeproducts", "honeys"],
        price: 5.95,
        previousPrice: 0,
        countInStock: 6,
        rating: 0,
        numReviews: 0,
        isPromo: false,
        isPublished: true,
        _id: "60d1cb018979637cf902ac65",
        name: "Royal jelly in honey",
        user: "60c654a986f5c3bd9967f046",
        image: "/public/images/ipadpro11_-7-1-1625310959416.jpg",
        description:
          "The health richness of royal jelly combined with natural honey. A great blend for making strengthening drinks. It has a simple composition and carefully selected ingredients.\n\nRoyal jelly is the secretion of the throat glands of young worker bees. It is a high-energy food for queen bees and younger larvae. Royal jelly  fresh is a substance with a creamy consistency and a variable color from light cream to light yellow. Slightly sour and tart in taste. Royal jelly contains many micro and macro elements, free amino acids, hormones, enzymes, organic acids, inhibitors, vitamins and other biologically active substances. Royal jelly in various forms is recommended during convalescence after serious diseases and after surgery. It is used in diseases of old age and helps maintain hormonal balance. It also regulates blood pressure and physical and mental activities, which leads to the elimination of fatigue and improvement of well-being. Clinical trials confirm the effectiveness of royal jelly in the treatment of patients with atherosclerosis, diabetes, Buerger's disease, angina and bronchial asthma.\n\nOrigin: Poland\n\nIngredients: pure honey 98%, royal jelly 2%\n\nEnergy value in 100g of product is around 1388 kJ / 327 kcal, fat 0.1 g, including saturated fats <0.1 g; carbohydrates 81 g, including sugars 77 g; protein 0.4 g; salt.0.011 g",
        brand: "",
        capacity: "220 g",
        capacityDropdown: [],
        countryOfOrigin: "",
        reviews: [],
        createdAt: "2021-06-22T11:35:29.544Z",
        updatedAt: "2021-07-20T10:26:53.630Z",
        __v: 1,
      },
    ],
    page: 1,
    pages: 1,
  },
}

export default testResponse
